server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecomerce_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      file-size-threshold: 1KB
eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
